In [12]:
import numpy as np

def pivoteamento(A, k, i):

  n = np.shape(A)[0] - 1 #último index
  print('n Ultimo ', n, '\n')

  #slicing
  print( np.array( A[ i : n + 1, k ] ) )

  #Localizando o  maior valor na coluna do pivô, depois do pivô
  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )
  print( 'colAbs \n', colAbs )

  indexMax = np.argmax( colAbs )
  print( indexMax )


  #Trocando a coluna
  iChange = indexMax + i
  #print( ,iChange )

  aux = np.copy( A[ k, : ] )
  #print( aux )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )

  print(A)

  return A


def applyGaussElimination( A, b, n ): #Linha do pivô
    for k in np.arange( 1, n ): #

        for i in np.arange( k + 1, n + 1 ): 

            A = pivoteamento(A,k,i) 
            m = A[ i, k ] / A[ k, k ] 
            A[ i, k ] = 0
            for j in np.arange( k + 1, n + 1 ):
                print('j', j )
        
    return A



b = np.array( [ 5., 6., 7., 15. ] )

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])

A = Amat
print(A)

n = np.shape(A)[0] - 1#último index
print('n ', n)

applyGaussElimination( np.copy( A ), np.copy( b ), n )


[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3
n Ultimo  3 

[-3  2]
colAbs 
 [3 2]
0
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  1  0  3]
 [ 0  2  4  0]]
j 2
j 3
n Ultimo  3 

[2]
colAbs 
 [2]
0
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0  0  3]
 [ 0 -3 -5  7]]
j 2
j 3
n Ultimo  3 

[-5]
colAbs 
 [5]
0
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0 -5  7]
 [ 0  0  0  3]]
j 3


array([[ 3,  2,  4, -1],
       [ 0,  2,  4,  0],
       [ 0,  0, -5,  7],
       [ 0,  0,  0,  3]])

In [7]:

import numpy as np
def resolution (a,b):
    n = len(a)
    m = n*[0]

    for k in range(0,n-1):
      for i in range(k+1,n):
        if(a[k][k]==0):
            return print("Pivo igual a zero")
        m = a[i][k]/a[k][k]
        if(a[i][k]==0):
            continue
        a[i][k]=0
        for j in range(k+1,n):
            a[i][j] = a[i][j] - (m*a[k][j])
        b[i] = b[i] - (m*b[k])


    return a

a = np.array([[2,(1),(-3)], [0,3,(2)], [(3),(1),(-3)]])
b = np.array([-1,12,0])

print("Matriz inicial")
print(a)
print("")
print("Matriz final / P.S: Está arredondando os valores")

print(resolution(a,b))

#Matriz final,se não estivesse arredondando para baixo, seria:
#[[ 2,  1,   -3],
#[ 0,  7/2, 1/2], -----> 7/2 => 3,5 => 3
#[ 0,  0,  11/7]])

Matriz inicial
[[ 2  1 -3]
 [ 0  3  2]
 [ 3  1 -3]]

Matriz final / P.S: Está arredondando os valores
[[ 2  1 -3]
 [ 0  3  2]
 [ 0  0  1]]


In [5]:
import numpy as np
def resolution (a,b):
    n = len(a)
    m = n*[0]
    if(np.linalg.det(a)==0):
     return print("Determinante igual a zero")
    else:
        for k in range(0,n-1):
          for i in range(k+1,n):
            m = a[i][k]/a[k][k]
            a[i][k]=0
            for j in range(k+1,n):
              a[i][j] = a[i][j] - (m*a[k][j])
            b[i] = b[i] - (m*b[k])


    return a

a = np.array([[2,(1),(-3)], [-1,3,(2)], [(0),(0),(0)]])
b = np.array([-1,12,0])

print("Matriz inicial")
print(a)
print("")

print(resolution(a,b))


Matriz inicial
[[ 2  1 -3]
 [-1  3  2]
 [ 0  0  0]]

Determinante igual a zero
None


In [8]:
import numpy as np
def resolution (a,b):
    n = len(a)
    m = n*[0]

    for k in range(0,n-1):
      for i in range(k+1,n):
        m = a[i][k]/a[k][k]
        a[i][k]=0
        for j in range(k+1,n):
            a[i][j] = a[i][j] - (m*a[k][j])
        b[i] = b[i] - (m*b[k])


    return a

a = np.array([[2.,(1.),(-1.)], [(-3.),(-1.),(2.)], [(-2.),(1.),(2.)]])
b = np.array([8.,(-1.),11.])

print("Matriz inicial")
print(a)
print("")
print("Matriz final / P.S: Está arredondando os valores")

print(resolution(a,b))

'''Nao termina com o exemplo simplificado do wiki gaussian elimination pois quando o looping termina, ele considera apenas que
   a matriz está em forma triangular. '''

Matriz inicial
[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]

Matriz final / P.S: Está arredondando os valores
[[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   0.  -1. ]]


'Nao termina com o exemplo simplificado do wiki gaussian elimination pois quando o looping termina, ele considera apenas que\n   a matriz está em forma triangular. '