In [2]:
import numpy as np

def pivoteamento(A, k, i):

  n = np.shape(A)[0] - 1 #último index
  print('n Ultimo ', n, '\n')

  #slicing
  print( np.array( A[ i : n + 1, k ] ) )

  #Localizando o  maior valor na coluna do pivô, depois do pivô
  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )
  print( 'colAbs \n', colAbs )

  indexMax = np.argmax( colAbs )
  print( indexMax )


  #Trocando a coluna
  iChange = indexMax + i
  #print( ,iChange )

  aux = np.copy( A[ k, : ] )
  #print( aux )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )

  print(A)

  return A


def applyGaussElimination( A, b, n ): #Linha do pivô
    for k in np.arange( 1, n ): #

        for i in np.arange( k + 1, n + 1 ): 

            A = pivoteamento(A,k,i) 
            m = A[ i, k ] / A[ k, k ] 
            A[ i, k ] = 0
            for j in np.arange( k + 1, n + 1 ):
                print('j', j )
        
    return A



b = np.array( [ 5., 6,] )

Amat = np.array([[0.0002, 2.], [2., 2.]])

A = Amat
print(A)

n = np.shape(A)[0] - 1#último index
print('n ', n)

applyGaussElimination( np.copy( A ), np.copy( b ), n )


[[2.e-04 2.e+00]
 [2.e+00 2.e+00]]
n  1


array([[2.e-04, 2.e+00],
       [2.e+00, 2.e+00]])

In [0]:

import numpy as np
def resolution (a,b):
    n = len(a)
    m = n*[0]

    for k in range(0,n-1):
      for i in range(k+1,n):
        if(a[k][k]==0):
            return print("Pivo igual a zero")
        m = a[i][k]/a[k][k]
        if(a[i][k]==0):
            continue
        a[i][k]=0
        for j in range(k+1,n):
            a[i][j] = a[i][j] - (m*a[k][j])
        b[i] = b[i] - (m*b[k])


    return a

b = np.array( [ 5, 6] )

a = np.array([[0.0002, 2], [2, 2]])

print("Matriz inicial")
print(a)
print("")
print("Matriz final / P.S: Está arredondando os valores")

print(resolution(a,b))

#Matriz final,se não estivesse arredondando para baixo, seria:
#[[ 2,  1,   -3],
#[ 0,  7/2, 1/2], -----> 7/2 => 3,5 => 3
#[ 0,  0,  11/7]])

Matriz inicial
[[2.e-04 2.e+00]
 [2.e+00 2.e+00]]

Matriz final / P.S: Está arredondando os valores
[[ 2.0000e-04  2.0000e+00]
 [ 0.0000e+00 -1.9998e+04]]


In [0]:
import numpy as np
def resolution (a,b):
    n = len(a)
    m = n*[0]
    if(np.linalg.det(a)==0):
     return print("Determinante igual a zero")
    else:
        for k in range(0,n-1):
          for i in range(k+1,n):
            m = a[i][k]/a[k][k]
            a[i][k]=0
            for j in range(k+1,n):
              a[i][j] = a[i][j] - (m*a[k][j])
            b[i] = b[i] - (m*b[k])


    return a

a = np.array([[2,(1),(-3)], [-1,3,(2)], [(0),(0),(0)]])
b = np.array([-1,12,0])

print("Matriz inicial")
print(a)
print("")

print(resolution(a,b))


Matriz inicial
[[ 2  1 -3]
 [-1  3  2]
 [ 0  0  0]]

Determinante igual a zero
None


In [0]:
import numpy as np
def resolution (a,b):
    n = len(a)
    m = n*[0]

    for k in range(0,n-1):
      for i in range(k+1,n):
        m = a[i][k]/a[k][k]
        a[i][k]=0
        for j in range(k+1,n):
            a[i][j] = a[i][j] - (m*a[k][j])
        b[i] = b[i] - (m*b[k])


    return a

a = np.array([[2.,(1.),(-1.)], [(-3.),(-1.),(2.)], [(-2.),(1.),(2.)]])
b = np.array([8.,(-1.),11.])

print("Matriz inicial")
print(a)
print("")
print("Matriz final / P.S: Está arredondando os valores")

print(resolution(a,b))

'''Nao termina com o exemplo simplificado do wiki gaussian elimination pois quando o looping termina, ele considera apenas que
   a matriz está em forma triangular. '''

Matriz inicial
[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]

Matriz final / P.S: Está arredondando os valores
[[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   0.  -1. ]]


'Nao termina com o exemplo simplificado do wiki gaussian elimination pois quando o looping termina, ele considera apenas que\n   a matriz está em forma triangular. '

In [3]:
import numpy as np
import random

def truncation(num, expoente, dig_lim):
  sinal = ''
  if (int(num.split('.')[0])>0 or (int(num.split('.')[0])<0) ) :

    tamanho_int=str(len(num.split('.')[0]))
    
    if(num[0] == '-'):
      sinal = num[0]

      num = num.replace(num[0],"")
      part_frac = num.split('.')[0]

    elif(num[0]==0 and num[0] != '-'):
        part_frac=num.split('.')[0] + num.split('.')[1] 
    else:
        part_frac=num.split('.')[0] 

    if(len(part_frac)>dig_lim): 
      part_frac=part_frac[:dig_lim] 

    if(int(tamanho_int)>expoente):
      frac = float(sinal + '0.'+part_frac)
      new_exp = int(expoente) 
      part_frac= sinal +'0.' + part_frac + '*10^' + str(expoente)
    else: 
      frac = float(sinal +'0.'+part_frac)
      new_exp = int(tamanho_int) 
      part_frac= sinal + '0.' + part_frac + '*10^' + tamanho_int

  else:

    part_frac=num.split('.')[1] 
    i=0
    while (True):
      if (part_frac[i]=='0'): i+=1
      else: break
    part_frac=part_frac.replace('0', '', i)

    if (len(part_frac)>dig_lim): 
      part_frac=part_frac[:dig_lim]

    if (i>=expoente): 
      frac = float(sinal + '0.'+part_frac)
      new_exp = int('-'+ expoente) 
      part_frac= sinal + '0.' + part_frac + '*10^-' + str(expoente)
    elif (i==0): 
      frac = float(sinal + '0.'+part_frac)
      new_exp = 0 
      part_frac= sinal + '0.' + part_frac + '*10^0'
    else: 
      frac = float(sinal + '0.'+part_frac)
      str(i)
      new_exp = int('-'+str(i)) 
      part_frac = sinal + '0.' + part_frac + '*10^-' + str(i)


  return frac, new_exp, part_frac



def pivoteamento(A, k, i, n):

  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )

  indexMax = np.argmax( colAbs )
  iChange = indexMax + i
  aux = np.copy( A[ k, : ] )
  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )


  return A


def applyGaussElimination( A, b, n ): 
    for k in np.arange( 0 , n ): 
        for i in np.arange( k + 1, n + 1 ): 
            A = pivoteamento(A, k, i, n)
            (num_i,exp_i,resp) = truncation(str(A[i][k]),5,3)
            (num_k,exp_k,resp) = truncation(str(A[k][k]),5,3) 
            m = (num_i*(10**exp_i)) / (num_k*(10**exp_k))
            A[ i, k ] = 0
        
    return A, b

def resp_final(A, b):
  
  A, b = applyGaussElimination(A, b, 1)



A = np.array([[0.0002, 2.], [2., 2.]])
b = np.array([5., 6.])

resp_final(A, b)

reserva2 = np.array([['         ', '          '], ['       ', '    ']])

n = len(A)

for k in range(0,n):
  for j in range(0,n):
    
    if(A[k][j]!=0):
      (num_i,exp_i,resp) = truncation(str(A[k][j]),5,3)
      reserva2[k][j] =  resp
    else:
     reserva2[k][j] = str(A[k][j])

print("\n Pivoteamento:")
print("\n",reserva2)


def resolution (a,b, dig): #Sem ser pivoteamento
    corret = 0
    n = len(a)
    m = n*[0]

    for k in range(0,n-1):
      for i in range(k+1,n):
        if(a[k][k]==0):
            return print("Pivo igual a zero")
        (num_i,exp_i,resp) = truncation(str(a[i][k]),5,3)
        (num_k,exp_k,resp) = truncation(str(a[k][k]),5,3)
        m = (num_i*(10**exp_i)) / (num_k*(10**exp_k))
        if(a[i][k]==0):
            continue
        a[i][k]=0
        for j in range(k+1,n):
            (num_multiplicador, exp_multiplicador, resp) = truncation(str(m),5,3)
            (num_i, exp_i, resp) = truncation(str(a[i][j]),5,3)
            (num_k, exp_k, resp) = truncation(str(a[k][j]),5,3)
            Expoentes = exp_multiplicador + exp_k
            Num = num_multiplicador*num_k
            if( exp_i < Expoentes):

              newExpoente = exp_i - Expoentes
              newValor = num_i * 10**newExpoente
              a[i][j] = (newValor*(10**Expoentes)) - Num*(10**Expoentes)
            elif(Expoentes < exp_i):

              newExpoente = Expoentes - exp_i
              newValor = Num * 10**newExpoente
              a[i][j] = (num_i*(10**exp_i)) - newValor*(10**newExpoente)
            else:
              a[i][j] = (num_i*(10**exp_i)) - Num*(10**Expoentes)
            newValor = str(newValor)
            if(len(newValor[2:(len(newValor))]) > dig):

                corret = 1
            
        
        (num_multiplicador, exp_multiplicador, resp) = truncation(str(m),5,3)
        (num_i, exp_i, resp) = truncation(str(b[i]),5,3)
        (num_k, exp_k, resp) = truncation(str(b[k]),5,3)
        Expoentes = exp_multiplicador + exp_k
        Num = num_multiplicador*num_k        
        if( exp_i < Expoentes):
          newExpoente = exp_i - Expoentes
          newValor = num_i * 10**newExpoente
          b[i] = (newValor*(10**Expoentes)) - Num*(10**Expoentes)
        elif(Expoentes < exp_i):
          newExpoente = Expoentes - exp_i
          newValor = Num * 10**newExpoente
          b[i] = (num_i*(10**exp_i)) - newValor*(10**newExpoente)
        else:
          b[i] = (num_i*(10**exp_i)) - Num*(10**Expoentes)
        newValor = str(newValor)
        if(len(newValor[2:(len(newValor))]) > dig):
          corret = 1

    return a, corret

b = np.array( [ 5, 6] )
corret = 0
a = np.array([[0.0002, 2.], [2., 2.]])
print("\n Matriz inicial:")
print("\n",a)
print("\n Matriz final / P.S: Está arredondando os valores:")

(matr,confirm) = resolution(a,b,3)

print("\n",matr) 
n = len(a)
A_digitos = np.array([['         ', '          '], ['       ', '    ']])

for k in range(0,n):
  for j in range(0,n):
    
    if(matr[k][j]!=0):
      (num_i,exp_i,resp) = truncation(str(matr[k][j]),5,3)
      A_digitos[k][j] =  resp
    else:
     A_digitos[k][j] = str(matr[k][j])



print("\n Conotação em digitos:")
print("\n",A_digitos)

if(corret == 0):
  print("\n Resposta está correta")
else:
  print("\n Resposta está incorreta")




 Pivoteamento:

 [['0.2*10^1' '0.2*10^1']
 ['0.0' '0.2*10^1']]

 Matriz inicial:

 [[2.e-04 2.e+00]
 [2.e+00 2.e+00]]

 Matriz final / P.S: Está arredondando os valores:

 [[ 2.0000e-04  2.0000e+00]
 [ 0.0000e+00 -1.9998e+04]]

 Conotação em digitos:

 [['0.2*10^-3' '0.2*10^1']
 ['0.0' '-0.199*10^']]

 Resposta está correta
